# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/nicholasuhlarik/Library/CloudStorage/OneDrive-UniversityofDerby/Audio\ Software/MyPlugins/ALL_SDK/VST_SDK/vst3sdk/pluginterfaces/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.7/share/cmake/Modules/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.7/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))

/Users/nicholasuhlarik/Library/CloudStorage/OneDrive-UniversityofDerby/Audio\ Software/MyPlugins/ALL_SDK/myprojects/StereoWidth/mac_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.27.7/bin/cmake -S/Users/nicholasuhlarik/Library/CloudStorage/OneDrive-UniversityofDerby/Audio\ Software/MyPlugins/ALL_SDK/myprojects/StereoWidth -B/Users/nicholasuhlarik/Library/CloudStorage/OneDrive-UniversityofDerby/Audio\ Software/MyPlugins/ALL_SDK/myprojects/StereoWidth/mac_build
